#coding:utf-8

ResourceDir="./resource"

buttonMap={
    1001:{
        'btnId':1001,
        'btnName':'btnMinimize',
        'btnGeometry':(565,-4,32,32),
        'btnToolTip':u"最小化",
        'onMouseShow':False,
        'btnImgSource':"%s/btnMinimize.png"%ResourceDir},
    1002:{
        'btnId':1002,
        'btnName':'btnClose',
        'btnGeometry':(590,-4,32,32),
        'btnToolTip':u"关闭",
        'onMouseShow':False,
        'btnImgSource':"%s/btnClose.png"%ResourceDir},
    1003:{
        'btnId':1003,
        'btnName':'btnInsertTopic',
        'btnGeometry':(2,60,75,25),
        'btnToolTip':u"插入话题",
        'onMouseShow':False,
        'btnImgSource':"%s/btnInsertTopic.png"%ResourceDir},
    1004:{
        'btnId':1004,
        'btnName':'btnInsertImg',
        'btnGeometry':(2,90,75,25),
        'btnToolTip':u"插入图片",
        'onMouseShow':False,
        'btnImgSource':"%s/btnInsertImg.png"%ResourceDir},
    1005:{
        'btnId':1005,
        'btnName':'btnAtFriend',
        'btnGeometry':(2,120,75,25),
        'btnToolTip':u"@好友",
        'onMouseShow':False,
        'btnImgSource':"%s/btnAtFriend.png"%ResourceDir},
    1006:{
        'btnId':1006,
        'btnName':'btnUpdate',
        'btnGeometry':(2,180,75,25),
        'btnToolTip':u"按Enter直接发布状态",
        'onMouseShow':False,
        'btnImgSource':"%s/btnUpdate.png"%ResourceDir},
    1007:{
        'btnId':1007,
        'btnName':'btnShowSelectedImage',
        'btnGeometry':(25,25,150,18),
        'btnToolTip':u"左单击查看图片，右单击清除图片",
        'onMouseShow':False,
        'btnImgSource':"%s/btnNone.png"%ResourceDir},
    1008:{
        'btnId':1008,
        'btnName':'btnGrabScreen',
        'btnGeometry':(2,150,75,25),
        'btnToolTip':u"截图发布",
        'onMouseShow':False,
        'btnImgSource':"%s/btnGrabScreen.png"%ResourceDir},
    }